// Trivial proxy server | Spencer Tipping
// Licensed under the terms of the MIT source code license

caterwaul.clone('std seq continuation montenegro')(function (require) {
  let*[http                      = require('http'),
       forward_request(req, res) = let*[parts = /\/([^\/]+)(\/.*)?/.exec(req.url), server = parts && parts[1], url = parts && parts[2] || '/'] in
                                   http.createClient(80, server).request(req.method, url, req.headers /se[_.host = server]) /se.r[
                                     req.on('data', r/mb/write), req.on('end', r/mb/end),
                                     r.on('response', _) /cps.response[res.writeHead(response.statusCode, response.headers),
                                                                       response.on('data', res/mb/write), response.on('end', res/mb/end)]]] in
  caterwaul.montenegro.server(30080) /se.server[
    seq[~'GET POST PUT DELETE'.split(/\s/) *![server.on(/./, _, forward_request)]]]})(require);

// Generated by SDoc 
